version: '3'

services:
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"


  worker:
    build: worker/
    container_name: worker
    environment:
      - "CELERY_BROKER_URL=redis://redis"
    command: celery -A predict worker -l INFO
    depends_on:
      - redis
  
  web:
    build: web/
    container_name: web
    environment:
      DEVICE: cpu
    ports:
      - 8080:80
    command: python app.py
    depends_on:
      - redis
      - worker
    
  front:
    build: front/
    container_name: front
    environment:
      IS_SHAREABLE: False
    ports:
      - 7860:7860
    command: python front_app.py
    depends_on:
      - redis
      - worker
      - web
      