version: '3'

services:
  web:
    build: web/
    container_name: web
    environment:
      DEVICE: cpu
    ports:
      - 8080:80
    command: python app.py
  
  front:
    build: front/
    container_name: front
    environment:
      IS_SHAREABLE: False
    ports:
      - 7860:7860
    command: python front_app.py
    depends_on:
      - web

  